### ISSUE TITLE
Queries aren't executed until Check is called

### ISSUE THREAD

**Issue by sazzer** [thepeak99/node-postgres-test#1]
I've just come across this module, and it seemed an ideal fit for testing my DAOs work correctly. In order to achieve this, I've done:

* Reset pgmock
* Expect a query and give it a result to return
* Call the DAO to load the data
* Assert that the loaded data is correct
* Call pgmock.check() to check that the queries are correct

From this, I've discovered that the queries are not actually executed until check() is called, which means that I've got no way of testing that the results are used correctly by the DAO layer.

**Comment by thepeak99** [comment]
Hi!

That is correct and actually intended. 

The idea is that you would first set up your expects, call your function providing a callback to validate the output and then start the whole process with `check()`. 

So first you would call `expect()` a few times, providing the queries and the mock responses (optionally), then you would call your function, and finally you call `check()` that will resolve the queries and call your function's callbacks. Something like this (using `chai`) :

    pgtest.expect('SELECT * FROM users WHERE username = $1', ['testUser']).returning(null, []);
    getUser('testUser', function(err, data) { //Your function
       expect.data.to.be.equal([]);
    });
    pgtest.check();

Is this what you were asking? Otherwise if you want you can provide your code and I take a look :)

**Comment by sazzer** [comment]
Hi there,

This is what my test code looks like:

```
suite('User DAO', () => {
    setup(() => {
        reset();
    });

    test('Load Unknown User by ID', () => {
        expectQuery('SELECT user_id, version, created, updated, name, email, providers FROM users WHERE user_id = $1', [1])
            .returning(null, []);

        return rewire()
            .use(userDao, {
                query
            })
            .run(async () => {
                const user = await findById(1);
                expect(user.isSome(), 'to be false');
            });
    });

    teardown(() => {
        checkQueries();
    });

});
```

I've then got a module that wraps your code very loosely, as follows: (Because in my actual code I've got an equivalent module that makes it easier to execute queries and get promises back than would normally be the case)

```
import pgtest from 'pgtest';

// Set up to expect the given query
export function expectQuery(sql, values) {
    return pgtest.expect(sql, values);
}

// Reset the expected queries
export function reset() {
    pgtest.reset();
}

// Check that the expected queries have been called
export function checkQueries() {
    pgtest.check();
}

// Execute the given query
export function query(sql, values) {
    return new Promise((resolve, reject) => {
        pgtest.connect('foo', (err, client, done) => {
            if (err) {
                done();
                reject(err);
            } else {
                client.query(sql, values, (err2, res) => {
                    done();
                    if (err2) {
                        reject(err2);
                    } else {
                        resolve(res);
                    }
                });
            }
        });
    });
}
```

I guess the problem comes down to my using async/await in my tests. The `await findById(1)` call doesn't resolve until the `checkQueries()` call is executed, after which everything has already timed out.

**Comment by sazzer** [comment]
For the record, thanks to what you've said I can get the tests working by changing them to:

```
suite('User DAO', () => {
    setup(() => {
        reset();
    });

    test('Load Unknown User by ID', () => {
        expectQuery('SELECT user_id, version, created, updated, name, email, providers FROM users WHERE user_id = $1', [1])
            .returning(null, []);

        return rewire()
            .use(userDao, {
                query
            })
            .run(() => {
                const result = findById(1)
                    .then((user) => {
                        expect(user.isSome(), 'to be false');
                    });

                checkQueries();
                return result;
            });
    });

});
```

**Comment by thepeak99** [comment]
Yep, you're totally right, since you were using async/await, that would "lock" and it would never call `check()`. 

I should probably update this lib to use promises, and that would prevent this from happening in the future.

In any case your solution will work just fine! :+1:

**Comment by thepeak99** [comment]
I'll close this issue for now, and (in the future) try to improve the code by using promises and ES6 (the code is a bit old indeed). In any case, feel free to let me know if you have more issues.
