### ISSUE TITLE
Regex generation from queries doesn't match parens correctly

### ISSUE THREAD

**Issue by sazzer** [thepeak99/node-postgres-test#2]
I'm trying to test the query
```sql
INSERT INTO users(version, created, updated, name, email, providers) VALUES ($1, $2, $2, $3, $4, $5) RETURNING user_id
```

And the regex that is generated is
```
/^INSERT INTO users(version, created, updated, name, email, providers) VALUES (\$1, \$2, \$2, \$3, \$4, \$5) RETURNING user_id$/
```

This doesn't work correctly, because the parens aren't escaped. Instead it needs to be
```
/^INSERT INTO users\(version, created, updated, name, email, providers\) VALUES \(\$1, \$2, \$2, \$3, \$4, \$5\) RETURNING user_id$/
```

**Comment by sazzer** [comment]
I've proven this by locally changing line 14 of node_modules/pgtest/lib/pgtest.js to:
```javascript
            s = args[0].replace(/\$/g, '\\$').replace(/\*/g, '\\*').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
```

And this makes my tests work.

**Comment by thepeak99** [comment]
Oh nice catch! I'll update and make a release.

**Comment by sazzer** [comment]
If you don't mind the dependency, I've just come across https://www.npmjs.com/package/escape-string-regexp that might make it more bulletproof. It covers quite a few other characters too.

**Comment by thepeak99** [comment]
Sure, seems legit!

**Comment by thepeak99** [comment]
Ok bug fixed, tests updated and release done :)
