### ISSUE TITLE
Error: Cannot find module 'assertion-error'

### ISSUE THREAD

**Issue by sazzer** [thepeak99/node-postgres-test#3]
I've just done a completely clean build to get the latest release of pgtest, and I'm now getting told that "assertion-error" is missing. I believe this is because it's a devDependency, even though it's required in "lib/pgtest.js"

**Comment by thepeak99** [comment]
Oh I messed up, I mistakenly moved that package to devDependencies. Fixing! Sorry :-(

**Comment by thepeak99** [comment]
Fixed in 0.2.2 :)
